[package]
name = "rust-tinynix-macro-impl"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.95"
rust-tinynix-core = { path = "../rust-tinynix-core" }
syn = "2.0"
