[package]
name = "rust-nix-macro-impl"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
pest = "2.7"
pest_derive = "2.7"
proc-macro2 = "1.0"
indexmap = "2.9.0"
