[package]
name = "piconix"
version = "0.1.0"
edition = "2024"

[dependencies]
piconix-core = { path = "../piconix-core" }
piconix-macro-impl = { path = "../piconix-macro-impl" }
indexmap = "2.2.6"

[[bin]]
name = "run-macro-test"
path = "src/main.rs"
