[package]
name = "rust-tinynix-core"
version = "0.1.0"
edition = "2024"

[dependencies]
home = "0.5.11"
indexmap = "2.2.6"
lazy_static = "1.5.0"
pest = "2.7"
pest_derive = "2.7"
proc-macro2 = "1.0"
quote = "1.0"
